# Generated by Django 2.2.5 on 2019-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190917_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
