# Generated by Django 2.2.5 on 2019-09-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190921_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Мобильные/Смартфоны', 'Мобильные/Смартфоны'), ('Компьютеры/Ноутбуки', 'Компьютеры/Ноутбуки'), ('Украшения/Бижутерия', 'Украшения/Бижутерия'), ('Обувь', 'Обувь'), ('Телевизоры', 'Телевизоры'), ('Аудио/Видео', 'Аудио/Видео')], default='Аудио/Видео', max_length=45),
        ),
    ]
