# Generated by Django 2.2.5 on 2019-09-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190921_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
