# Generated by Django 2.2.5 on 2019-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20191003_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
